-- AlterTable
ALTER TABLE "setting" ALTER COLUMN "deliveryFee" SET DEFAULT 0,
ALTER COLUMN "deliveryFee" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "serviceFee" SET DEFAULT 0,
ALTER COLUMN "serviceFee" SET DATA TYPE DECIMAL(65,30);
